### ISSUE TITLE
ERROR Class 'Evoweb\StoreFinder\Service\Provider\Provider' not found 

### ISSUE THREAD

**Issue by danielpesel** [evoWeb/store_finder#13]
Hi,
i am trying to test the extention on my web site but i am geting this error
Class 'Evoweb\StoreFinder\Service\Provider\Provider' not found 
what is missing?

Thanks for your help

**Comment by garbast** [comment]
You need to configure in typoscript what map provider you want to use https://github.com/evoWeb/store_finder/blob/be16d12a2c1a7c90c53fe371d2e0414d99dd2263/Configuration/TypoScript/setup.typoscript#L7

**Comment by danielpesel** [comment]
Hi, Thanks for the other day.
I have another problem now. the map will not load. Unfortunately, I have no error message that I could pass on here. The space for the Mape is resaviert but everything is empty

**Comment by garbast** [comment]
Sorry, but there is nothing i can do with this information.
If you realy cant solve it, I could offer you professional paid support to check your system.
