### ISSUE TITLE
Cannot cast object of type "TYPO3\CMS\Extbase\Persistence\Generic\LazyObjectStorage" to string.

### ISSUE THREAD

**Issue by worldwideweber** [evoWeb/store_finder#15]
Hi, 
if i add a Record Storage Page, i get this Exception in v9.5.9 
Cannot cast object of type "TYPO3\CMS\Extbase\Persistence\Generic\LazyObjectStorage" to string.
Without a Record Storage Page the Form is displayed, but the Map don load, i see only a grey Rectangle.

What am i doing wrong?

Thanks for your help

**Comment by garbast** [comment]
Cant reproduce the problem in current develop branch. You need locations that are geocoded. If the map is grey there must be a javascript error and you need to sortout your configuration that these do not happen.
