### ISSUE TITLE
Error after Update to Version 4.0.2

### ISSUE THREAD

**Issue by elgato42** [evoWeb/store_finder#17]
Hi, after the update to version 4.0.2 i get an error if i try to search for location.

Typo3 Version: 9.5.10
PHP Version: 7.3.10

This is the error:

```
Oops, an error occurred!
Class 'Http\Adapter\Guzzle6\Client' not found
```

**Comment by garbast** [comment]
Tried to reproduce the error in 9.5.11 with dev-develop but cant run in this situation. As long as you are doing a composer update you should have everything needed.
