### ISSUE TITLE
make locale of geocoder configurable :feature

### ISSUE THREAD

**Issue by mym91** [evoWeb/store_finder#18]
To have more precise results its possible to permit a locale to the geocoder. In \Evoweb\StoreFinder\Service\GeocodeService::getCoordinatesFromProvider you set the locale always to 'en'. Please make it configurable.

**Comment by garbast** [comment]
I like your idea.

Please add a parameter in store_finder/ext_conf_template.txt as this is used in the geocode command and hand in the PR after that.
