### ISSUE TITLE
rtrim() expects parameter 1 to be string, null given 

### ISSUE THREAD

**Issue by danielpesel** [evoWeb/store_finder#20]
Hi, when i try to cange to Nominatim i get this error

rtrim() expects parameter 1 to be string, null given

in the backend "Core: Exception handler (WEB): Uncaught TYPO3 Exception: rtrim() expects parameter 1 to be string, null given | TypeError thrown in file /var/www/vhosts/pluspunktleben.de/gego.pluspunktleben.de/vendor/geocoder-php/nominatim-provider/Nominatim.php in line 72. Requested URL: https://gego.pluspunktleben.de/index.php?id=4&no_cache=1"

this is showing

can you help me?

**Comment by garbast** [comment]
As i dont know the api of the NominatimProvider i can only guess that is has to do with https://github.com/evoWeb/store_finder/blob/develop/Classes/Service/GeocodeService.php line 181. I need to know what to put there and then make it configurable via typoscript.

So if you tell me what to put there i can patch it in.

**Comment by danielpesel** [comment]
do you mean this one?
https://github.com/geocoder-php/nominatim-provider/blob/master/Nominatim.php from line 68.
hope that it helps

thanks anyway

ps: did you got my email?

**Comment by danielpesel** [comment]
hy again,

i'm sorry to disturb you but could you do anything, was my information of any help?

thanks

**Comment by evoWeb** [comment]
Maybe you have misinterpreted my comment. I need some patch or code fragment that shows what needs to be changed. I do not have time to elaborate a fix.

**Comment by danielpesel** [comment]
Okay, thanks but i solve it with something else. For the moment its fine. When i have more time i will try to find the exact code that is needed.
