### ISSUE TITLE
how to search stores nearby according to my current position

### ISSUE THREAD

**Issue by zzzzzyue** [evoWeb/store_finder#21]
Hi , is it possible , if i want to search stores nearby according to my current position?
Now i could only search them by giving adress and this adress should be already geocoded in database.
If there is a way to get my current positon and calculate it in backend code , and showing in the map the nearest store (for example 10km), which are already in database geocoded.

Thank you for help and have a nice day : )

**Comment by garbast** [comment]
First of, it's not possible to get your current location with php. You have to get it via javascript and you have to deliver this javascript yourself as it's not part of the extension.

Then is possible to use these coordinates as hidden field values for latitute and longitude and search with these.

That should solve your problem.
