### ISSUE TITLE
No Content Object definition found at TypoScript object path "tt_content.list.20.storefinder_show"

### ISSUE THREAD

**Issue by wechselstroom** [evoWeb/store_finder#24]
in version 4.1.1 the show plugin is not registered and typo3 throws an exception. (see title)

fix is to register the show plugin by adding the following code to ext_localconf.php:

`    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extensionName,
        'Show',
        [$mapController => 'show'],
        [$mapController => 'show']
        );`

**Comment by garbast** [comment]
Is in addition to develop in branch dev-4.x available
