### ISSUE TITLE
Zoom setting not int

### ISSUE THREAD

**Issue by wechselstroom** [evoWeb/store_finder#25]
In version 4.1.1 typo3 throws the following exception when using the show plugin (with corrected code from previous issue):
Argument 1 passed to Evoweb\StoreFinder\Domain\Model\Location::setZoom() must be of the type integer, string given, called in /app/web/public/typo3conf/ext/store_finder/Classes/Controller/MapController.php on line 299

fix: change line 299 in MapController.php to:
`$center->setZoom($this->settings['zoom'] ? (int) $this->settings['zoom'] : 15);`

**Comment by garbast** [comment]
Fixed in 249b3d5
