### ISSUE TITLE
sjbr/static-info-tables no existing version

### ISSUE THREAD

**Issue by rickymathewkweb** [evoWeb/store_finder#26]
It looks like _sjbr/static-info-tables_ is not available as version 6.8.7 . The latest version is 6.7.5 when i checked packagist today . So this seems to be a wrong dependency. Can you please fix this ?

**Comment by garbast** [comment]
If you would have read the https://github.com/evoWeb/store_finder/blob/develop/README.md you wouldn't have ask this.
