### ISSUE TITLE
Controll map display

### ISSUE THREAD

**Issue by febuchner** [evoWeb/store_finder#27]
It seems that in prior versions it was possible to configure the map section before a search was performed via

plugin.tx_storefinder.settings {
        showLocationsForDefaultConstraint = 1
        defaultConstraint {
                zoom = 15
                latitude = 51.5135
                longitude = 7.464
        }
}

At the moment it seems that this is not working anymore. Is there a way to simulate such a behaviour in the latest version and, in addition, to display the found stores after the search right away (without having to scroll to them)?

**Comment by garbast** [comment]
This is still the case if you select "Map" in "Show before search" in the flexform of the plugin

**Comment by febuchner** [comment]
Which is what I did, but sadly I doesn't work for me.

**Comment by garbast** [comment]
https://github.com/evoWeb/store_finder/blob/1b6c1391a9ea07c240b15145eecf692cd2b5f2d4/Classes/Controller/MapController.php#L354 uses the defaultConstraint and is still present. I cant see why its not working for you.
