### ISSUE TITLE
Search for storename

### ISSUE THREAD

**Issue by blueamerican** [evoWeb/store_finder#29]
I'm using store_finder 4.1.1
TYPO3 9.5.26

Standard configuration, without categories.

In the search mask, the input of the user given for "storename" does not have any influence on the search result.

Do i make something wrong?

Best regards

**Comment by garbast** [comment]
Your search still needs to be geolocatable. So you either neeed to set default constraints via TypoScript or let the user enter required city and zip in the search form.

https://github.com/evoWeb/store_finder/blob/249b3d59f5e01059dc7e7e505ecfbf900f3afddd/Classes/Domain/Repository/LocationRepository.php#L106

**Comment by blueamerican** [comment]
I do not understand this.

E.g. i have two stores.

Store Nr.1
Name: teststore
ZIP: 57627
loacation: Hachenburg

Store Nr.2
Name: xyz
ZIP: 57627
loacation: Hachenburg

If i now fill out the following in the search form:
Name: xyz
ZIP: 57627
loacation: Hachenburg

i only expect 1 result.

But actual i get both results. It seems, as if the constraint "name" does not have any influence on the search result.

Best regards

**Comment by stephangrass** [comment]
OK, it's not possible to search by store name only. But why are both zip code and city mandatory fields?
