### ISSUE TITLE
Fehler beim Speichern von Datensätzen.

### ISSUE THREAD

**Issue by Domtaholic** [evoWeb/store_finder#30]
Hi - beim Speichern eines Datensatzes der Übersetzt ist bekommen wir aktuell eine Fehlermeldung.

![image](https://user-images.githubusercontent.com/3584433/124779641-3c73f500-df42-11eb-82b4-31d7cae13244.png)

die "findByUidInBackend" im LocationRepo sollte ein "setRespectSyslanguage(false) im Query enthalten. Damit man die Datensätze auch ohne Fehlermeldung speichern kann.

**Comment by garbast** [comment]
Again, issue language is english!

Feel free to hand in a PR

**Comment by Domtaholic** [comment]
PR was accepted - issue can be closed.
