### ISSUE TITLE
Ter Extension not loading any dependency

### ISSUE THREAD

**Issue by ebincm** [evoWeb/store_finder#33]
Added the below paths to em_conf to make it work.Is there any other method to make it work 
[storedependency.tar.gz](https://github.com/evoWeb/store_finder/files/7787587/storedependency.tar.gz)

`'Http\\Adapter\\Guzzle7\\' => 'vendor/php-http/guzzle7-adapter/src',
'Psr\\Http\\Client\\' => 'vendor/psr/http-client/src',
'Http\\Promise\\' => 'vendor/php-http/promise/src',
'Http\\Client\\' => 'vendor/php-http/httplug/src',
'GuzzleHttp\\Psr7\\' =>  'vendor/guzzlehttp/psr7/src',
'GuzzleHttp\\Promise\\' =>  'vendor/guzzlehttp/promises/src',
'GuzzleHttp\\' =>  'vendor/guzzlehttp/guzzle/src',
'Psr\\Http\\Message\\' =>  array('vendor/psr/http-message/src', 'vendor/psr/http-factory/src'),
'Http\\Message\\' => array('vendor/php-http/message-factory/src','vendor/php-http/message/src'),
'Http\\Discovery\\' => 'vendor/php-http/discovery/src',
'Geocoder\\Provider\\GoogleMaps\\' => 'vendor/geocoder-php/google-maps-provider',
'Geocoder\\Http\\' => 'vendor/geocoder-php/common-http',
'Geocoder\\' => 'vendor/willdurand/geocoder',`

**Comment by garbast** [comment]
The extensions is intended to be used in composer context. If installed with composer the dependencies will be loaded fine.
