### ISSUE TITLE
How to import data correctly

### ISSUE THREAD

**Issue by stephangrass** [evoWeb/store_finder#37]
I'm trying to import data with this:

`storefinder:import '1:/user_upload/locations.xlsx' 203 1 '{A:"import_id",B:"name",C:"address",D:"city",E:"zipcode",F:"country",G:"phone",H:"email",I:"url",J:"icon"}' '' ''`

However, only empty data records are imported. And also more than are available in the Excel file. What am I doing wrong?

Thanks for a tip
Stephan

**Comment by stephangrass** [comment]
Ok, if I use

`storefinder:import '1:/user_upload/locations.xlsx' 203 1 '{"A":"import_id","B":"name","C":"address","D":"city","E":"zipcode","F":"country","G":"phone","H":"email","I":"url","J":"icon"}' '' ''`

I will get the error:
```
Uncaught TYPO3 Exception Cannot use object of type stdClass as array
thrown in file /homepages/17/d452800978/htdocs/websites/typo3/www/typo3conf/ext/store_finder/Classes/Command/ImportLocationsCommand.php
in line 253
```

**Comment by stephangrass** [comment]
When I edit ImportLocationsCommand

```
    private $columnMap = [
        'A' => 'import_id',
        'B' => 'name',
        'C' => 'address',
        'D' => 'city',
        'E' => 'zipcode',
        'F' => 'country',
        'G' => 'phone',
        'H' => 'email',
        'I' => 'url',
        'J' => 'icon',
    ];
```
the import will work. But not the country-transformation (DE, AT, LU, ...)

**Comment by garbast** [comment]
The importer was improved and the changes are documented. Please test if the console call without php changes work for you now. After that testing i would release the extension.

The countries need to be replaced in the excel sheet, there is nothing that could be done with reasonable efford. If you like to sponsore an automatic mapping, atleast three hours are needed for that.

**Comment by stephangrass** [comment]
Thanks!
This will work.
