### ISSUE TITLE
Store Finder 5.2 Extension not really working?

### ISSUE THREAD

**Issue by stephangrass** [evoWeb/store_finder#38]
Hi, 

after importing some data,I wanted to test the frontend. Unfortunately, errors appear immediately after a search.

If no image is assigned:

`Supplied TYPO3\CMS\Extbase\Domain\Model\FileReference:7032 could not be resolved to a File or FileReference. `

If I adjust this in the template:

`Exception while property mapping at property path "country": [Semantical Error] The annotation "@Lazy" in property SJBR\StaticInfoTables\Domain\Model\Country::$countryZones was never imported. Did you maybe forget to add a "use" statement for this annotation? `

Does it perhaps make no sense to use the extension in this version?

**Comment by garbast** [comment]
I close this issue, because it is not providing any information needed to solve the problem.
