### ISSUE TITLE
Show map with all locations

### ISSUE THREAD

**Issue by stephangrass** [evoWeb/store_finder#39]
Hi, one more question:

Can the map also show all locations before the search? Transnational?

Thanks
Stephan

**Comment by garbast** [comment]
By default it's possible to use the list directly without the search, but it will be always one nation only because a search needs to be performed and the geocoding api forces you to provide a country.

But it would be possible to xclass the location repository to circumvent that.

**Comment by stephangrass** [comment]
> But it would be possible to xclass the location repository to circumvent that.

Thanks. But is there a way to get a specific tip on how to do something like this?

**Comment by garbast** [comment]
This is not covered by the free support. If you need a custom solution, i can provide you paid support. Please contact me via the email address given in the ext_emconf, if you want this.
