### ISSUE TITLE
Undefined array key "location"

### ISSUE THREAD

**Issue by KamalNayanParmar** [evoWeb/store_finder#42]
Hello,

I am having TYPO3 11.5.28 project and PHP 8.1 configuration.
I have used store_finder 6.1.0 as it is only available for TYPO3 11.5 version.
When I install and configure the plugin and run in the front end I got a PHP warning like below.

`
PHP Warning: Undefined array key "location" in
/typo3conf/ext/store_finder/Classes/Controller/MapController.php line 204
`
Is anyone have a solution for this?

**Comment by garbast** [comment]
Change your php error settings. It is a warning not an error.
