### ISSUE TITLE
google.maps.Marker in the Maps JavaScript API (Deprecated as of February 2024)

### ISSUE THREAD

**Issue by LightsOnDeveloper** [evoWeb/store_finder#50]
Hi, as of February 2024 google.maps.Marker is considered deprecated and will be supported for the next 12 months. Are there any plans to optimize the JavScript?

**Comment by garbast** [comment]
I'll have a look into this when i start working on a release for TYPO3 13.

That said i will not backport it to older branches. In addition any help with the js part is welcome.

**Comment by garbast** [comment]
Needs to be refactored as mentioned in https://developers.google.com/maps/documentation/javascript/markers

**Comment by garbast** [comment]
Resolved in develop with commit 4f33f90
