### ISSUE TITLE
Composer dependency Issue in TYPO3 v12

### ISSUE THREAD

**Issue by KaiGrosz** [evoWeb/store_finder#57]
Hello,

if I install the Extension in TYPO3 v12, there is an composer error like: 

Problem 1
    - Root composer.json requires evoweb/store-finder 7.0.14 -> satisfiable by evoweb/store-finder[7.0.14].
    - evoweb/store-finder 7.0.14 requires sjbr/static-info-tables dev-master -> found sjbr/static-info-tables[dev-master] but it does not match your minimum-stability.

He want to require the package sjbr/static-info-tables in dev-master, thats TYPO3 v13 now, thats why the composer detects the requirements. To Fix this i think we have to change the composer.json in the 7.x Branch: 

composer.json:51
"sjbr/static-info-tables": "^12.4.4",

Thank u very much. 

Cheers

**Comment by garbast** [comment]
With release 7.1.2 the extension static_info_tables is only suggested.
